---
version: '2.4'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: tecken-loadtests:latest
    env_file:
      - my.env
    volumes:
      - $PWD:/app
    command: /bin/bash
